function addItem() {
    var spans = document.getElementsByTagName('span');
    $('<div><div class="col-sm-6"><input type="text"'
            + 'class=<div class="col-sm-6">'
            + '<label for="food_name">Type of Food:</label>'
					  + '<input type="text" id="food_name" name="food_name" class="form-control">'
					  + '</div>'
						+ '<div class="col-sm-6">'
					  + '<label for="quantity">Quantity:</label>'
						+ '<input type="text" id="quantity" name="quantity" class="form-control">'
						+ '</div>'
					  + '</span>'
						+ '</div>'
						+ '<div class="form-group row">'
						+ '<div class="col-sm-6">'
						+ '<label for="expire_date">Expiration Date:</label>'
						+ '<input type="expire_date" id="expire_date" name="expire_date" class="form-control">'
						+ '</div>'
					  + '<div class="col-sm-6">'
						+ '<label for="perishable">Is this food perishable?</label>'
						+ '<input type="checkbox" id="perishable" name="perishable" class="form-control">'
						+ '</div>'
						+ '</div>'
						+ '<div class="form-group row">'
					  + '<div class="col-sm-12">'
            + '<label for="comments">Comments:</label>'
            + '<input type="text" id="comments" name="comments" class="form-control">'
						+ '</div></div>').appendTo('.food_list');
}
